--- !ditz.rubyforge.org,2008-03-06/project 
name: pint
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: pint
- !ditz.rubyforge.org,2008-03-06/component 
  name: PINT language
- !ditz.rubyforge.org,2008-03-06/component 
  name: ph-reach
releases: []

